Note: Requires 'REST Client' for VSCode

### Register a new User
POST http://localhost:7071/api/user
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "Password123!",
    "fullName": "New User"
}

### SignIn a User
POST http://localhost:7071/api/Sign-In
Content-Type: application/json

{
    "email": "administrator@localhost", 
    "password": "Administrator1!"
}

### Get a User by id like bbe1a9d4-b480-4f89-9074-2f6971f5668d
GET http://localhost:7071/api/user/{bbe1a9d4-b480-4f89-9074-2f6971f5668d}

### Update a User
PUT http://localhost:7071/api/user
Content-Type: application/json

{
    "email": "newuser@example.com",
    "fullName": "Updated User"
}

### Delete User by id like bbe1a9d4-b480-4f89-9074-2f6971f5668d
DELETE http://localhost:7071/api/user/{bbe1a9d4-b480-4f89-9074-2f6971f5668d}
//Authorization: Bearer {{token}}

// Replace {id} with the actual user ID
